In [26]:
import pandas as pd
import glob
from bertopic import BERTopic
from sentence_transformers import SentenceTransformer

import openai
from bertopic.representation import OpenAI

from hdbscan import HDBSCAN

In [27]:
df_news = pd.read_parquet('./Data/all_news_1984_2024.parquet')
df_news['Date'] = pd.to_datetime(df_news['Date'], format='%Y-%m-%d')

In [10]:
year = 2001

df_gpr = pd.read_csv(f'./Result/GPR_Peaks/data/gpr_peaks_{year}.csv')
filtered_news = df_news[df_news['Date'].isin(df_gpr['date'])]
filtered_news

,Date,Caption,Content
887629,2001-09-12,Mistakes Made the Catastrophe Possible,It is likely that more Americans died yesterda...
887630,2001-09-12,How Did They Get Past Security?,"Now we know, someone said yesterday, why they ..."
887631,2001-09-12,Business World: What I Saw on the First Day of...,It's not every day in Manhattan that you look ...
887632,2001-09-12,"We Beat Hitler. We Can Vanquish This Foe, Too","America, it is said, is slow to awaken, and in..."
887633,2001-09-12,Civility Amid Chaos,Terrorists may have thought they were striking...
...,...,...,...
892574,2001-10-31,Argentine Agony,Argentine securities have hit the skids of lat...
892575,2001-10-31,Asides: Public Power Flickers,California's recent electricity crisis has rev...
892576,2001-10-31,The Case for Ground Troops,"During the Clinton years, the preferred milita..."
892577,2001-10-31,The Education of Jim McGreevey,"The way Jim McGreevey tells it, his childhood ..."
892578,2001-10-31,Theater: Strike Up the Funeral Marching Band -...,"New York -- `THOU SHALT NOT"" needed a Jeeves. ..."

In [ ]:
# GICS_SEED_KEYWORDS = [
#     # 能源 (Energy)
#     ["energy", "oil", "gas", "opec", "shale", "chevron", "exxon", "natural gas", "pipeline"],
#     # 金融 (Financials)
#     ["financial", "bank", "fed", "ecb", "inflation", "stock", "equity", "bond", "investment", "goldman", "jpmorgan", "debt", "rates"],
#     # 信息技术 (Information Technology)
#     ["tech", "apple", "google", "microsoft", "semiconductor", "chip", "software", "ai", "nvidia", "meta"],
#     # 工业 (Industrials)
#     ["industrial", "boeing", "lockheed", "defense", "aerospace", "airline", "manufacturing", "supply chain"],
#     # 医疗保健 (Health Care)
#     ["health", "pharma", "pfizer", "moderna", "biotech", "fda", "vaccine", "healthcare"],
#     # 非必需消费品 (Consumer Discretionary)
#     ["consumer", "tesla", "amazon", "alibaba", "retail", "auto", "carmaker"],
#     # 通信服务 (Communication Services)
#     ["telecom", "verizon", "at&t", "disney", "netflix", "google", "meta"],
#     # 原材料 (Materials)
#     ["materials", "mining", "rio tinto", "bhp", "commodity", "metals", "lithium"],
#     # 房地产 (Real Estate)
#     ["real estate", "commercial property", "housing", "reits"]
# ]

In [ ]:
docs = filtered_news['Content'].tolist()
timestamps = filtered_news['Date'].tolist()

# hdbscan_model = HDBSCAN(min_cluster_size=15, metric='euclidean', cluster_selection_method='eom', prediction_data=True)
# embedding_model = SentenceTransformer("BAAI/bge-base-en-v1.5")
embedding_model = SentenceTransformer("all-MiniLM-L6-v2")
topic_model = BERTopic(embedding_model=embedding_model, 
                       # min_topic_size=200,
                    #    nr_topics=20,
                        # seed_topic_list=GICS_SEED_KEYWORDS,
                        verbose=True)
topics, probs = topic_model.fit_transform(docs)
topic_info = topic_model.get_topic_info()
print("Topic Info:")
print(topic_info)

2025-07-02 22:53:48,445 - BERTopic - Embedding - Transforming documents to embeddings.

Batches:   0%|          | 0/131 [00:00<?, ?it/s]

2025-07-02 22:54:33,670 - BERTopic - Embedding - Completed ✓
2025-07-02 22:54:33,671 - BERTopic - Dimensionality - Fitting the dimensionality reduction algorithm
2025-07-02 22:54:34,720 - BERTopic - Dimensionality - Completed ✓
2025-07-02 22:54:34,721 - BERTopic - Cluster - Start clustering the reduced embeddings
2025-07-02 22:54:34,786 - BERTopic - Cluster - Completed ✓
2025-07-02 22:54:34,788 - BERTopic - Representation - Fine-tuning topics using representation models.
2025-07-02 22:54:35,471 - BERTopic - Representation - Completed ✓

Topic Info:
     Topic  Count                                     Name  \
0       -1   1096                         -1_the_of_to_and
1        0     98                         0_her_was_he_the
2        1     88               1_estate_space_real_square
3        2     88        2_security_airport_faa_passengers
4        3     87  3_taliban_pakistan_afghanistan_alliance
..     ...    ...                                      ...
102    101     11                  101_coke_dulce_leche_de
103    102     11            102_iran_iranian_turkey_blair
104    103     10                 103_billion_york_tax_new
105    104     10             104_loss_cents_million_share
106    105     10             105_or_nasdaq_gained_quarter

                                        Representation  \
0      [the, of, to, and, in, that, for, it, is, said]
1    [her, was, he, the, center, she, and, of, his,...
2    [estate, space, real, square, tenants, office,...
3    [security, airport, faa, passengers, airlines,...
4    [taliban, pakistan, afghanistan, alliance, afg...
..                                                 ...
102  [coke, dulce, leche, de, drink, powerade, bran...
103  [iran, iranian, turkey, blair, islamic, afghan...
104  [billion, york, tax, new, federal, house, bush...
105  [loss, cents, million, share, revenue, quarter...
106  [or, nasdaq, gained, quarter, cents, results, ...

                                   Representative_Docs
0    [Corrections & Amplifications SWISSAIR GROUP C...
1    [Tales of terror and heroics continue to emerg...
2    [More of Wall Street is moving away from Wall ...
3    [WASHINGTON -- The Federal Aviation Administra...
4    [LAHORE, Pakistan -- In the aftermath of the a...
..                                                 ...
102  [Coca-Cola Co. is in discussions to reassign a...
103  [For the first time in 22 years, a British for...
104  [WASHINGTON -- With some insurance leaders cal...
105  [Sybase Inc. swung to a third-quarter net loss...
106  [NEW YORK -- Those continuing reports about a ...

[107 rows x 5 columns]

In [66]:
topic_model.visualize_topics()

In [12]:
topic_model.topic_embeddings_

array([[-0.00710328, -0.02099075,  0.00372117, ..., -0.09165002,
        -0.01679543,  0.01814516],
       [-0.01499701, -0.0206952 ,  0.01457956, ..., -0.12852328,
        -0.0144714 ,  0.01559433],
       [-0.03804268, -0.04707636,  0.03129139, ..., -0.10243652,
        -0.01138562,  0.01216789],
       ...,
       [ 0.00487667, -0.01531598,  0.03141178, ..., -0.13084823,
        -0.06148916,  0.05292897],
       [ 0.07394592, -0.04786346,  0.03183304, ..., -0.00445615,
        -0.03005093,  0.00427538],
       [ 0.02253365,  0.00237644,  0.03121332, ..., -0.05266342,
        -0.0487191 ,  0.0067972 ]], dtype=float32)

In [95]:
# War Threats (Category 1), Peace Threats (Category 2), Military Buildups (Category 3), Nuclear Threats (Category 4), Terror Threats (Category 5), Beginning of War (Category 6), Escalation of War (Category 7), Terror Acts (Category 8)
GPR_categories = ['War Threats', 'Peace Threats', 'Military Buildups', 'Nuclear Threats', 'Terror Threats', 'Beginning of War', 'Escalation of War', 'Terror Acts']
# GPR_categories = ['Economic Policy & Budget', 'Environment', 'Trade', 'Institutions & Political Process', 'Health', 'Security & Defense', 'Tax Policy', 'Technology & Infrastructure']

# Compute the similarity between the topics and the GPR categories
# Using the topic embeddings from BERTopic
topic_embeddings = topic_model.topic_embeddings_
gpr_embeddings = [embedding_model.encode(category) for category in GPR_categories]

from sklearn.metrics.pairwise import cosine_similarity
similarities = cosine_similarity(topic_embeddings, gpr_embeddings)
# Show all topics with all GPR categories
similarity_df = pd.DataFrame(similarities, columns=GPR_categories)
similarity_df.index = [f'Topic {i}' for i in range(len(topic_embeddings))]
print("Similarity between topics and GPR categories:")
similarity_df.head(50)  # Show the first 10 topics for brevity

Similarity between topics and GPR categories:

,War Threats,Peace Threats,Military Buildups,Nuclear Threats,Terror Threats,Beginning of War,Escalation of War,Terror Acts
Topic 0,0.407445,0.382943,0.353620,0.373854,0.505942,0.201828,0.314179,0.403943
Topic 1,0.152226,0.137867,0.185044,0.172596,0.303672,0.175619,0.097915,0.312754
Topic 2,0.186158,0.211986,0.198169,0.174005,0.302318,0.080817,0.161023,0.258663
Topic 3,0.279980,0.288713,0.229067,0.295498,0.453540,0.084204,0.194392,0.341209
Topic 4,0.396796,0.453112,0.212338,0.296720,0.406994,0.292533,0.369925,0.341001
Topic 5,0.250987,0.213942,0.239426,0.263099,0.344631,0.178820,0.199245,0.304641
Topic 6,0.257520,0.259276,0.207796,0.240361,0.424922,0.189536,0.187954,0.447911
Topic 7,0.114746,0.035525,0.137593,0.147160,0.079110,0.072344,0.104701,0.065192
Topic 8,0.374131,0.442955,0.239783,0.264649,0.537508,0.185559,0.310001,0.482520
Topic 9,0.182414,0.138148,0.162790,0.172331,0.172594,0.111564,0.127534,0.085865
Topic 10,0.138370,0.121024,0.107715,0.145744,0.107712,0.081053,0.153782,0.054171
Topic 11,0.325652,0.303030,0.192866,0.258548,0.428094,0.118084,0.271012,0.365077
Topic 12,0.247355,0.253221,0.132728,0.237959,0.322337,0.065605,0.229450,0.187616
Topic 13,0.153974,0.125141,0.069862,0.104613,0.133422,0.075659,0.106569,0.060544
Topic 14,0.063777,0.043461,0.058276,0.049576,0.049510,0.011343,0.047715,0.007448
Topic 15,0.180052,0.118970,0.184611,0.207827,0.152680,0.129536,0.207515,0.051136
Topic 16,0.144491,0.103996,0.157748,0.107019,0.149596,0.126035,0.183363,0.065388
Topic 17,0.341038,0.328423,0.216322,0.289890,0.467943,0.150934,0.272970,0.406274
Topic 18,0.208625,0.189070,0.216104,0.163013,0.310748,0.131975,0.179450,0.309748
Topic 19,0.103438,0.085152,0.042182,0.045373,0.087495,0.060365,0.046807,0.050047
Topic 20,0.363199,0.329322,0.267876,0.287175,0.392341,0.270237,0.319556,0.410392
Topic 21,0.225372,0.184151,0.204407,0.186263,0.292142,0.186635,0.204405,0.257302
Topic 22,0.118786,0.070791,0.147086,0.082573,0.090936,0.110361,0.146833,0.115374
Topic 23,0.051435,0.048846,0.093872,0.026166,0.033044,0.027327,0.073946,0.044858
Topic 24,0.294577,0.190196,0.363917,0.215512,0.165627,0.189021,0.194242,0.110538
Topic 25,0.186075,0.164828,0.050578,0.136670,0.211111,0.083256,0.138948,0.181135
Topic 26,0.345273,0.361490,0.226303,0.220512,0.468892,0.232834,0.245883,0.433980
Topic 27,0.149010,0.120181,0.074343,0.186725,0.192417,0.105443,0.176474,0.161799
Topic 28,0.273862,0.253524,0.212648,0.217313,0.365588,0.214876,0.226985,0.341118
Topic 29,0.164684,0.108211,0.070466,0.150548,0.135778,0.044108,0.175566,0.111567
Topic 30,0.217640,0.203531,0.214456,0.155654,0.329020,0.162668,0.177071,0.347718
Topic 31,0.125198,0.101596,0.089233,0.164161,0.110751,0.082781,0.125796,0.091210
Topic 32,0.293738,0.242269,0.239042,0.251857,0.311352,0.173200,0.265913,0.279245
Topic 33,0.127504,0.091926,0.114656,0.105222,0.115500,0.063059,0.084843,0.060168
Topic 34,0.433330,0.273969,0.565565,0.376334,0.314819,0.273539,0.394283,0.278278
Topic 35,0.189661,0.206279,0.197727,0.222253,0.301477,0.101511,0.155875,0.280644
Topic 36,0.497201,0.470271,0.301899,0.461821,0.520639,0.271790,0.323664,0.391296
Topic 37,0.132023,0.113683,0.120538,0.106207,0.110079,0.103133,0.138075,0.033350
Topic 38,0.286507,0.319959,0.242468,0.243220,0.396488,0.229269,0.261160,0.340362
Topic 39,0.111582,0.079082,0.124856,0.057859,0.150934,0.089341,0.079485,0.124167
Topic 40,0.109526,0.065713,0.046501,0.100079,0.087005,0.087080,0.101277,0.109558
Topic 41,0.235252,0.175214,0.136748,0.205471,0.183503,0.176437,0.264721,0.165349
Topic 42,0.544486,0.588386,0.349956,0.483012,0.640226,0.314885,0.430728,0.552801
Topic 43,0.269452,0.234107,0.189723,0.216417,0.357219,0.155263,0.185744,0.286647
Topic 44,0.269370,0.280172,0.150143,0.276045,0.191672,0.218097,0.271828,0.132153
Topic 45,0.236958,0.158931,0.223879,0.180922,0.261120,0.115407,0.125582,0.194291
Topic 46,0.066403,0.044837,0.065512,0.032859,0.075443,-0.001042,-0.014193,0.051938
Topic 47,0.268439,0.246198,0.154214,0.169481,0.339041,0.165943,0.225923,0.248709
Topic 48,0.242494,0.191921,0.180436,0.216045,0.322409,0.090757,0.221340,0.298178
Topic 49,0.077804,0.079356,0.070454,0.065965,0.102197,0.074518,0.093869,0.165356

In [84]:
# get topic count
topic_counts = topic_model.get_topic_info().set_index('Topic')['Count']
# print(int(topic_counts[-1]))

# add topic counts to similarity_df
similarity_df['Topic Count'] = 0
# Iterate through the similarity_df and set the Topic Count
for idx, row in similarity_df.iterrows():
    # print(f"Processing {idx}...")
    idx_num = int(idx.split(' ')[-1]) - 1  # Extract the topic number from the index
    similarity_df.at[idx, 'Topic Count'] = int(topic_counts[idx_num])

similarity_df

,War Threats,Peace Threats,Military Buildups,Nuclear Threats,Terror Threats,Beginning of War,Escalation of War,Terror Acts,Topic Count
Topic 0,0.407445,0.382943,0.353620,0.373854,0.505942,0.201828,0.314179,0.403943,1096
Topic 1,0.152226,0.137867,0.185044,0.172596,0.303672,0.175619,0.097915,0.312754,98
Topic 2,0.186158,0.211986,0.198169,0.174005,0.302318,0.080817,0.161023,0.258663,88
Topic 3,0.279980,0.288713,0.229067,0.295498,0.453540,0.084204,0.194392,0.341209,88
Topic 4,0.396796,0.453112,0.212338,0.296720,0.406994,0.292533,0.369925,0.341001,87
...,...,...,...,...,...,...,...,...,...
Topic 102,0.109937,0.099911,0.115224,0.090374,0.117416,0.124450,0.168963,0.100742,11
Topic 103,0.438931,0.422880,0.356742,0.469906,0.474147,0.239160,0.375693,0.380113,11
Topic 104,0.276555,0.240952,0.411128,0.212350,0.290978,0.158867,0.233859,0.255767,10
Topic 105,0.075789,0.049002,0.122411,0.080879,0.095903,0.049521,0.052969,0.017043,10
Topic 106,0.098313,0.086399,0.126945,0.067077,0.137857,0.037739,0.082204,0.107952,10

In [25]:
similarity_df.to_excel(f'similarity_df_{year}.xlsx', index=True)

In [90]:
# Sort the similarity_df by the first GPR categories
similarity_df_sorted = similarity_df.sort_values(by=GPR_categories[0], ascending=False)
similarity_df_sorted.head(5)

,War Threats,Peace Threats,Military Buildups,Nuclear Threats,Terror Threats,Beginning of War,Escalation of War,Terror Acts,Topic Count
Topic 42,0.544486,0.588386,0.349956,0.483012,0.640226,0.314885,0.430728,0.552801,31
Topic 36,0.497201,0.470271,0.301899,0.461821,0.520639,0.271790,0.323664,0.391296,32
Topic 58,0.442863,0.496717,0.346416,0.310726,0.522256,0.286597,0.381482,0.447683,24
Topic 103,0.438931,0.422880,0.356742,0.469906,0.474147,0.239160,0.375693,0.380113,11
Topic 34,0.433330,0.273969,0.565565,0.376334,0.314819,0.273539,0.394283,0.278278,33

In [75]:
def topic_differences(model, original_topics, nr_topics=5):
    """Show the differences in topic representations between two models """
    df = pd.DataFrame(columns=["Topic", "Original", "Updated"])
    for topic in range(nr_topics):

        # Extract top 5 words per topic per model
        og_words = " | ".join(list(zip(*original_topics[topic]))[0][:2])
        new_words = " | ".join(list(zip(*model.get_topic(topic)))[0][:2])
        df.loc[len(df)] = [topic, og_words, new_words]

    return df

In [76]:
from copy import deepcopy
original_topics = deepcopy(topic_model.topic_representations_)

prompt = """
I have a topic that contains the following documents:
[DOCUMENTS]

The topic is described by the following keywords: [KEYWORDS]

Based on the information above, extract a short topic label in the following format:
topic: <short topic label>
"""

# Update our topic representations using GPT-3.5
client = openai.OpenAI(api_key="YOUR_OPENAI_API_KEY")

representation_model = OpenAI(
    client, model='gpt-4o' ,exponential_backoff=True, chat=True, prompt=prompt
)

topic_model.update_topics(docs, representation_model=representation_model)

# Show topic differences
# topic_differences(topic_model, original_topics)

100%|██████████| 107/107 [03:42<00:00,  2.08s/it]

In [77]:
df_result = topic_model.get_topic_info()
# drop Representative_Docs
df_result = df_result.drop(columns=['Representative_Docs'], errors='ignore')
# Save the result to a CSV file
df_result.to_csv(f'./result_{year}_v1.csv')
df_result

,Topic,Count,Name,Representation
0,-1,1096,-1_Post-9/11 Economic Impact and Security Meas...,[Post-9/11 Economic Impact and Security Measures]
1,0,98,0_September 11 World Trade Center Attack Survi...,[September 11 World Trade Center Attack Surviv...
2,1,88,1_Post-9/11 Manhattan Real Estate Impact and A...,[Post-9/11 Manhattan Real Estate Impact and Ad...
3,2,88,2_Post-9/11 Airline Security Measures,[Post-9/11 Airline Security Measures]
4,3,87,3_Afghanistan-Pakistan Relations and the Talib...,[Afghanistan-Pakistan Relations and the Taliba...
...,...,...,...,...
102,101,11,101_Coca-Cola's Advertising Consolidation and ...,[Coca-Cola's Advertising Consolidation and Dul...
103,102,11,102_U.S.-Iran Relations and Counterterrorism E...,[U.S.-Iran Relations and Counterterrorism Effo...
104,103,10,103_Post-9/11 Economic Aid and Infrastructure ...,[Post-9/11 Economic Aid and Infrastructure Reb...
105,104,10,104_Financial Performance and Market Reaction ...,[Financial Performance and Market Reaction of ...
106,105,10,105_Stock Market Performance and Earnings Reports,[Stock Market Performance and Earnings Reports]

In [26]:
for year in range(2008, 2025):
    print(f"Processing year: {year}")
    
    df_gpr = pd.read_csv(f'./Result/GPR_Peaks/data/gpr_peaks_{year}.csv')
    filtered_news = df_news[df_news['Date'].isin(df_gpr['date'])]
    docs = filtered_news['Content'].tolist()
    timestamps = filtered_news['Date'].tolist()

    embedding_model = SentenceTransformer("all-MiniLM-L6-v2")
    topic_model = BERTopic(embedding_model=embedding_model, 
                           # min_topic_size=200,
                           nr_topics=5,
                           verbose=True)
    topics, probs = topic_model.fit_transform(docs)
    topic_info = topic_model.get_topic_info()

    original_topics = deepcopy(topic_model.topic_representations_)

    prompt = """
    I have a topic that contains the following documents:
    [DOCUMENTS]

    The topic is described by the following keywords: [KEYWORDS]

    Based on the information above, extract a short topic label in the following format:
    topic: <short topic label>
    """

    # Update our topic representations using GPT-3.5
    client = openai.OpenAI(api_key="YOUR_OPENAI_API_KEY")

    representation_model = OpenAI(
        client, model='gpt-4o' ,exponential_backoff=True, chat=True, prompt=prompt
    )

    topic_model.update_topics(docs, representation_model=representation_model)

    df_result = topic_model.get_topic_info()
    # drop Representative_Docs
    df_result = df_result.drop(columns=['Representative_Docs'], errors='ignore')
    # Save the result to a CSV file
    df_result.to_csv(f'./result_{year}.csv')

Processing year: 2008

2025-06-30 20:18:28,970 - BERTopic - Embedding - Transforming documents to embeddings.
Batches: 100%|██████████| 112/112 [00:21<00:00,  5.30it/s]
2025-06-30 20:18:50,388 - BERTopic - Embedding - Completed ✓
2025-06-30 20:18:50,388 - BERTopic - Dimensionality - Fitting the dimensionality reduction algorithm
2025-06-30 20:18:57,753 - BERTopic - Dimensionality - Completed ✓
2025-06-30 20:18:57,754 - BERTopic - Cluster - Start clustering the reduced embeddings
2025-06-30 20:18:57,818 - BERTopic - Cluster - Completed ✓
2025-06-30 20:18:57,819 - BERTopic - Representation - Extracting topics using c-TF-IDF for topic reduction.
2025-06-30 20:18:58,486 - BERTopic - Representation - Completed ✓
2025-06-30 20:18:58,487 - BERTopic - Topic reduction - Reducing number of topics
2025-06-30 20:18:58,490 - BERTopic - Representation - Fine-tuning topics using representation models.
2025-06-30 20:18:59,090 - BERTopic - Representation - Completed ✓
2025-06-30 20:18:59,092 - BERTopic - Topic reduction - Reduced number of topics from 78 to 5
100%|██████████| 5/5 [00:05<00:00,  1.15s/it]

Processing year: 2009

2025-06-30 20:19:07,832 - BERTopic - Embedding - Transforming documents to embeddings.
Batches: 100%|██████████| 156/156 [00:27<00:00,  5.61it/s]
2025-06-30 20:19:36,023 - BERTopic - Embedding - Completed ✓
2025-06-30 20:19:36,024 - BERTopic - Dimensionality - Fitting the dimensionality reduction algorithm
2025-06-30 20:19:37,575 - BERTopic - Dimensionality - Completed ✓
2025-06-30 20:19:37,575 - BERTopic - Cluster - Start clustering the reduced embeddings
2025-06-30 20:19:37,667 - BERTopic - Cluster - Completed ✓
2025-06-30 20:19:37,668 - BERTopic - Representation - Extracting topics using c-TF-IDF for topic reduction.
2025-06-30 20:19:38,510 - BERTopic - Representation - Completed ✓
2025-06-30 20:19:38,511 - BERTopic - Topic reduction - Reducing number of topics
2025-06-30 20:19:38,515 - BERTopic - Representation - Fine-tuning topics using representation models.
2025-06-30 20:19:39,331 - BERTopic - Representation - Completed ✓
2025-06-30 20:19:39,332 - BERTopic - Topic reduction - Reduced number of topics from 142 to 5
100%|██████████| 5/5 [00:07<00:00,  1.44s/it]

Processing year: 2010

2025-06-30 20:19:49,831 - BERTopic - Embedding - Transforming documents to embeddings.
Batches: 100%|██████████| 328/328 [00:55<00:00,  5.91it/s]
2025-06-30 20:20:46,124 - BERTopic - Embedding - Completed ✓
2025-06-30 20:20:46,125 - BERTopic - Dimensionality - Fitting the dimensionality reduction algorithm
2025-06-30 20:20:48,195 - BERTopic - Dimensionality - Completed ✓
2025-06-30 20:20:48,196 - BERTopic - Cluster - Start clustering the reduced embeddings
2025-06-30 20:20:48,400 - BERTopic - Cluster - Completed ✓
2025-06-30 20:20:48,400 - BERTopic - Representation - Extracting topics using c-TF-IDF for topic reduction.
2025-06-30 20:20:50,138 - BERTopic - Representation - Completed ✓
2025-06-30 20:20:50,140 - BERTopic - Topic reduction - Reducing number of topics
2025-06-30 20:20:50,149 - BERTopic - Representation - Fine-tuning topics using representation models.
2025-06-30 20:20:51,999 - BERTopic - Representation - Completed ✓
2025-06-30 20:20:52,003 - BERTopic - Topic reduction - Reduced number of topics from 357 to 5
100%|██████████| 5/5 [00:05<00:00,  1.08s/it]

Processing year: 2011

2025-06-30 20:21:01,690 - BERTopic - Embedding - Transforming documents to embeddings.
Batches: 100%|██████████| 235/235 [00:41<00:00,  5.68it/s]
2025-06-30 20:21:43,609 - BERTopic - Embedding - Completed ✓
2025-06-30 20:21:43,610 - BERTopic - Dimensionality - Fitting the dimensionality reduction algorithm
2025-06-30 20:21:45,846 - BERTopic - Dimensionality - Completed ✓
2025-06-30 20:21:45,847 - BERTopic - Cluster - Start clustering the reduced embeddings
2025-06-30 20:21:45,969 - BERTopic - Cluster - Completed ✓
2025-06-30 20:21:45,969 - BERTopic - Representation - Extracting topics using c-TF-IDF for topic reduction.
2025-06-30 20:21:47,296 - BERTopic - Representation - Completed ✓
2025-06-30 20:21:47,297 - BERTopic - Topic reduction - Reducing number of topics
2025-06-30 20:21:47,303 - BERTopic - Representation - Fine-tuning topics using representation models.
2025-06-30 20:21:48,584 - BERTopic - Representation - Completed ✓
2025-06-30 20:21:48,587 - BERTopic - Topic reduction - Reduced number of topics from 218 to 5
100%|██████████| 5/5 [00:06<00:00,  1.33s/it]

Processing year: 2012

2025-06-30 20:21:59,046 - BERTopic - Embedding - Transforming documents to embeddings.
Batches: 100%|██████████| 117/117 [00:20<00:00,  5.61it/s]
2025-06-30 20:22:20,212 - BERTopic - Embedding - Completed ✓
2025-06-30 20:22:20,212 - BERTopic - Dimensionality - Fitting the dimensionality reduction algorithm
2025-06-30 20:22:27,943 - BERTopic - Dimensionality - Completed ✓
2025-06-30 20:22:27,944 - BERTopic - Cluster - Start clustering the reduced embeddings
2025-06-30 20:22:28,004 - BERTopic - Cluster - Completed ✓
2025-06-30 20:22:28,005 - BERTopic - Representation - Extracting topics using c-TF-IDF for topic reduction.
2025-06-30 20:22:28,775 - BERTopic - Representation - Completed ✓
2025-06-30 20:22:28,776 - BERTopic - Topic reduction - Reducing number of topics
2025-06-30 20:22:28,780 - BERTopic - Representation - Fine-tuning topics using representation models.
2025-06-30 20:22:29,492 - BERTopic - Representation - Completed ✓
2025-06-30 20:22:29,493 - BERTopic - Topic reduction - Reduced number of topics from 80 to 5
100%|██████████| 5/5 [00:05<00:00,  1.16s/it]

Processing year: 2013

2025-06-30 20:22:38,471 - BERTopic - Embedding - Transforming documents to embeddings.
Batches: 100%|██████████| 123/123 [00:21<00:00,  5.62it/s]
2025-06-30 20:23:00,633 - BERTopic - Embedding - Completed ✓
2025-06-30 20:23:00,634 - BERTopic - Dimensionality - Fitting the dimensionality reduction algorithm
2025-06-30 20:23:09,132 - BERTopic - Dimensionality - Completed ✓
2025-06-30 20:23:09,132 - BERTopic - Cluster - Start clustering the reduced embeddings
2025-06-30 20:23:09,197 - BERTopic - Cluster - Completed ✓
2025-06-30 20:23:09,198 - BERTopic - Representation - Extracting topics using c-TF-IDF for topic reduction.
2025-06-30 20:23:09,938 - BERTopic - Representation - Completed ✓
2025-06-30 20:23:09,939 - BERTopic - Topic reduction - Reducing number of topics
2025-06-30 20:23:09,942 - BERTopic - Representation - Fine-tuning topics using representation models.
2025-06-30 20:23:10,697 - BERTopic - Representation - Completed ✓
2025-06-30 20:23:10,699 - BERTopic - Topic reduction - Reduced number of topics from 83 to 5
100%|██████████| 5/5 [00:05<00:00,  1.04s/it]

Processing year: 2014

2025-06-30 20:23:19,253 - BERTopic - Embedding - Transforming documents to embeddings.
Batches: 100%|██████████| 126/126 [00:22<00:00,  5.65it/s]
2025-06-30 20:23:41,865 - BERTopic - Embedding - Completed ✓
2025-06-30 20:23:41,866 - BERTopic - Dimensionality - Fitting the dimensionality reduction algorithm
2025-06-30 20:23:50,651 - BERTopic - Dimensionality - Completed ✓
2025-06-30 20:23:50,652 - BERTopic - Cluster - Start clustering the reduced embeddings
2025-06-30 20:23:50,720 - BERTopic - Cluster - Completed ✓
2025-06-30 20:23:50,720 - BERTopic - Representation - Extracting topics using c-TF-IDF for topic reduction.
2025-06-30 20:23:51,463 - BERTopic - Representation - Completed ✓
2025-06-30 20:23:51,464 - BERTopic - Topic reduction - Reducing number of topics
2025-06-30 20:23:51,468 - BERTopic - Representation - Fine-tuning topics using representation models.
2025-06-30 20:23:52,154 - BERTopic - Representation - Completed ✓
2025-06-30 20:23:52,155 - BERTopic - Topic reduction - Reduced number of topics from 92 to 5
100%|██████████| 5/5 [00:06<00:00,  1.24s/it]

Processing year: 2015

2025-06-30 20:24:01,347 - BERTopic - Embedding - Transforming documents to embeddings.
Batches: 100%|██████████| 115/115 [00:19<00:00,  5.78it/s]
2025-06-30 20:24:21,496 - BERTopic - Embedding - Completed ✓
2025-06-30 20:24:21,497 - BERTopic - Dimensionality - Fitting the dimensionality reduction algorithm
2025-06-30 20:24:28,955 - BERTopic - Dimensionality - Completed ✓
2025-06-30 20:24:28,955 - BERTopic - Cluster - Start clustering the reduced embeddings
2025-06-30 20:24:29,013 - BERTopic - Cluster - Completed ✓
2025-06-30 20:24:29,013 - BERTopic - Representation - Extracting topics using c-TF-IDF for topic reduction.
2025-06-30 20:24:29,703 - BERTopic - Representation - Completed ✓
2025-06-30 20:24:29,704 - BERTopic - Topic reduction - Reducing number of topics
2025-06-30 20:24:29,708 - BERTopic - Representation - Fine-tuning topics using representation models.
2025-06-30 20:24:30,367 - BERTopic - Representation - Completed ✓
2025-06-30 20:24:30,369 - BERTopic - Topic reduction - Reduced number of topics from 79 to 5
100%|██████████| 5/5 [00:06<00:00,  1.36s/it]

Processing year: 2016

2025-06-30 20:24:40,309 - BERTopic - Embedding - Transforming documents to embeddings.
Batches: 100%|██████████| 110/110 [00:18<00:00,  5.79it/s]
2025-06-30 20:24:59,547 - BERTopic - Embedding - Completed ✓
2025-06-30 20:24:59,547 - BERTopic - Dimensionality - Fitting the dimensionality reduction algorithm
2025-06-30 20:25:06,383 - BERTopic - Dimensionality - Completed ✓
2025-06-30 20:25:06,384 - BERTopic - Cluster - Start clustering the reduced embeddings
2025-06-30 20:25:06,440 - BERTopic - Cluster - Completed ✓
2025-06-30 20:25:06,441 - BERTopic - Representation - Extracting topics using c-TF-IDF for topic reduction.
2025-06-30 20:25:07,057 - BERTopic - Representation - Completed ✓
2025-06-30 20:25:07,058 - BERTopic - Topic reduction - Reducing number of topics
2025-06-30 20:25:07,061 - BERTopic - Representation - Fine-tuning topics using representation models.
2025-06-30 20:25:07,665 - BERTopic - Representation - Completed ✓
2025-06-30 20:25:07,666 - BERTopic - Topic reduction - Reduced number of topics from 74 to 5
100%|██████████| 5/5 [00:05<00:00,  1.14s/it]

Processing year: 2017

2025-06-30 20:25:16,375 - BERTopic - Embedding - Transforming documents to embeddings.
Batches: 100%|██████████| 111/111 [00:19<00:00,  5.79it/s]
2025-06-30 20:25:35,775 - BERTopic - Embedding - Completed ✓
2025-06-30 20:25:35,776 - BERTopic - Dimensionality - Fitting the dimensionality reduction algorithm
2025-06-30 20:25:42,811 - BERTopic - Dimensionality - Completed ✓
2025-06-30 20:25:42,812 - BERTopic - Cluster - Start clustering the reduced embeddings
2025-06-30 20:25:42,868 - BERTopic - Cluster - Completed ✓
2025-06-30 20:25:42,868 - BERTopic - Representation - Extracting topics using c-TF-IDF for topic reduction.
2025-06-30 20:25:43,458 - BERTopic - Representation - Completed ✓
2025-06-30 20:25:43,458 - BERTopic - Topic reduction - Reducing number of topics
2025-06-30 20:25:43,462 - BERTopic - Representation - Fine-tuning topics using representation models.
2025-06-30 20:25:44,027 - BERTopic - Representation - Completed ✓
2025-06-30 20:25:44,028 - BERTopic - Topic reduction - Reduced number of topics from 85 to 5
100%|██████████| 5/5 [00:07<00:00,  1.50s/it]

Processing year: 2018

2025-06-30 20:25:54,382 - BERTopic - Embedding - Transforming documents to embeddings.
Batches: 100%|██████████| 98/98 [00:16<00:00,  5.99it/s]
2025-06-30 20:26:10,964 - BERTopic - Embedding - Completed ✓
2025-06-30 20:26:10,965 - BERTopic - Dimensionality - Fitting the dimensionality reduction algorithm
2025-06-30 20:26:16,511 - BERTopic - Dimensionality - Completed ✓
2025-06-30 20:26:16,511 - BERTopic - Cluster - Start clustering the reduced embeddings
2025-06-30 20:26:16,562 - BERTopic - Cluster - Completed ✓
2025-06-30 20:26:16,563 - BERTopic - Representation - Extracting topics using c-TF-IDF for topic reduction.
2025-06-30 20:26:17,095 - BERTopic - Representation - Completed ✓
2025-06-30 20:26:17,096 - BERTopic - Topic reduction - Reducing number of topics
2025-06-30 20:26:17,099 - BERTopic - Representation - Fine-tuning topics using representation models.
2025-06-30 20:26:17,590 - BERTopic - Representation - Completed ✓
2025-06-30 20:26:17,591 - BERTopic - Topic reduction - Reduced number of topics from 72 to 5
100%|██████████| 5/5 [00:06<00:00,  1.37s/it]

Processing year: 2019

2025-06-30 20:26:27,553 - BERTopic - Embedding - Transforming documents to embeddings.
Batches: 100%|██████████| 96/96 [00:16<00:00,  5.67it/s]
2025-06-30 20:26:44,699 - BERTopic - Embedding - Completed ✓
2025-06-30 20:26:44,699 - BERTopic - Dimensionality - Fitting the dimensionality reduction algorithm
2025-06-30 20:26:50,023 - BERTopic - Dimensionality - Completed ✓
2025-06-30 20:26:50,024 - BERTopic - Cluster - Start clustering the reduced embeddings
2025-06-30 20:26:50,072 - BERTopic - Cluster - Completed ✓
2025-06-30 20:26:50,073 - BERTopic - Representation - Extracting topics using c-TF-IDF for topic reduction.
2025-06-30 20:26:50,615 - BERTopic - Representation - Completed ✓
2025-06-30 20:26:50,616 - BERTopic - Topic reduction - Reducing number of topics
2025-06-30 20:26:50,619 - BERTopic - Representation - Fine-tuning topics using representation models.
2025-06-30 20:26:51,113 - BERTopic - Representation - Completed ✓
2025-06-30 20:26:51,115 - BERTopic - Topic reduction - Reduced number of topics from 76 to 5
100%|██████████| 5/5 [00:06<00:00,  1.27s/it]

Processing year: 2020

2025-06-30 20:27:00,267 - BERTopic - Embedding - Transforming documents to embeddings.
Batches: 100%|██████████| 93/93 [00:15<00:00,  6.08it/s]
2025-06-30 20:27:15,808 - BERTopic - Embedding - Completed ✓
2025-06-30 20:27:15,808 - BERTopic - Dimensionality - Fitting the dimensionality reduction algorithm
2025-06-30 20:27:20,897 - BERTopic - Dimensionality - Completed ✓
2025-06-30 20:27:20,898 - BERTopic - Cluster - Start clustering the reduced embeddings
2025-06-30 20:27:20,946 - BERTopic - Cluster - Completed ✓
2025-06-30 20:27:20,947 - BERTopic - Representation - Extracting topics using c-TF-IDF for topic reduction.
2025-06-30 20:27:21,493 - BERTopic - Representation - Completed ✓
2025-06-30 20:27:21,493 - BERTopic - Topic reduction - Reducing number of topics
2025-06-30 20:27:21,497 - BERTopic - Representation - Fine-tuning topics using representation models.
2025-06-30 20:27:22,019 - BERTopic - Representation - Completed ✓
2025-06-30 20:27:22,020 - BERTopic - Topic reduction - Reduced number of topics from 62 to 5
100%|██████████| 5/5 [00:06<00:00,  1.21s/it]

Processing year: 2021

2025-06-30 20:27:31,526 - BERTopic - Embedding - Transforming documents to embeddings.
Batches: 100%|██████████| 43/43 [00:07<00:00,  6.07it/s]
2025-06-30 20:27:38,715 - BERTopic - Embedding - Completed ✓
2025-06-30 20:27:38,715 - BERTopic - Dimensionality - Fitting the dimensionality reduction algorithm
2025-06-30 20:27:40,197 - BERTopic - Dimensionality - Completed ✓
2025-06-30 20:27:40,198 - BERTopic - Cluster - Start clustering the reduced embeddings
2025-06-30 20:27:40,218 - BERTopic - Cluster - Completed ✓
2025-06-30 20:27:40,218 - BERTopic - Representation - Extracting topics using c-TF-IDF for topic reduction.
2025-06-30 20:27:40,476 - BERTopic - Representation - Completed ✓
2025-06-30 20:27:40,476 - BERTopic - Topic reduction - Reducing number of topics
2025-06-30 20:27:40,479 - BERTopic - Representation - Fine-tuning topics using representation models.
2025-06-30 20:27:40,731 - BERTopic - Representation - Completed ✓
2025-06-30 20:27:40,732 - BERTopic - Topic reduction - Reduced number of topics from 21 to 5
100%|██████████| 5/5 [00:11<00:00,  2.23s/it]

Processing year: 2022

2025-06-30 20:27:54,515 - BERTopic - Embedding - Transforming documents to embeddings.
Batches: 100%|██████████| 81/81 [00:14<00:00,  5.67it/s]
2025-06-30 20:28:09,013 - BERTopic - Embedding - Completed ✓
2025-06-30 20:28:09,013 - BERTopic - Dimensionality - Fitting the dimensionality reduction algorithm
2025-06-30 20:28:12,965 - BERTopic - Dimensionality - Completed ✓
2025-06-30 20:28:12,965 - BERTopic - Cluster - Start clustering the reduced embeddings
2025-06-30 20:28:13,004 - BERTopic - Cluster - Completed ✓
2025-06-30 20:28:13,005 - BERTopic - Representation - Extracting topics using c-TF-IDF for topic reduction.
2025-06-30 20:28:13,553 - BERTopic - Representation - Completed ✓
2025-06-30 20:28:13,554 - BERTopic - Topic reduction - Reducing number of topics
2025-06-30 20:28:13,557 - BERTopic - Representation - Fine-tuning topics using representation models.
2025-06-30 20:28:14,099 - BERTopic - Representation - Completed ✓
2025-06-30 20:28:14,100 - BERTopic - Topic reduction - Reduced number of topics from 53 to 5
100%|██████████| 5/5 [00:05<00:00,  1.19s/it]

Processing year: 2023

2025-06-30 20:28:22,967 - BERTopic - Embedding - Transforming documents to embeddings.
Batches: 100%|██████████| 96/96 [00:14<00:00,  6.49it/s]
2025-06-30 20:28:37,844 - BERTopic - Embedding - Completed ✓
2025-06-30 20:28:37,845 - BERTopic - Dimensionality - Fitting the dimensionality reduction algorithm
2025-06-30 20:28:43,154 - BERTopic - Dimensionality - Completed ✓
2025-06-30 20:28:43,154 - BERTopic - Cluster - Start clustering the reduced embeddings
2025-06-30 20:28:43,203 - BERTopic - Cluster - Completed ✓
2025-06-30 20:28:43,203 - BERTopic - Representation - Extracting topics using c-TF-IDF for topic reduction.
2025-06-30 20:28:43,417 - BERTopic - Representation - Completed ✓
2025-06-30 20:28:43,418 - BERTopic - Topic reduction - Reducing number of topics
2025-06-30 20:28:43,422 - BERTopic - Representation - Fine-tuning topics using representation models.
2025-06-30 20:28:43,615 - BERTopic - Representation - Completed ✓
2025-06-30 20:28:43,616 - BERTopic - Topic reduction - Reduced number of topics from 60 to 5
100%|██████████| 5/5 [00:06<00:00,  1.36s/it]

Processing year: 2024

2025-06-30 20:28:52,801 - BERTopic - Embedding - Transforming documents to embeddings.
Batches: 100%|██████████| 46/46 [00:07<00:00,  6.26it/s]
2025-06-30 20:29:00,161 - BERTopic - Embedding - Completed ✓
2025-06-30 20:29:00,162 - BERTopic - Dimensionality - Fitting the dimensionality reduction algorithm
2025-06-30 20:29:01,784 - BERTopic - Dimensionality - Completed ✓
2025-06-30 20:29:01,784 - BERTopic - Cluster - Start clustering the reduced embeddings
2025-06-30 20:29:01,807 - BERTopic - Cluster - Completed ✓
2025-06-30 20:29:01,807 - BERTopic - Representation - Extracting topics using c-TF-IDF for topic reduction.
2025-06-30 20:29:01,833 - BERTopic - Representation - Completed ✓
2025-06-30 20:29:01,833 - BERTopic - Topic reduction - Reducing number of topics
2025-06-30 20:29:01,834 - BERTopic - Topic reduction - Number of topics (5) is equal or higher than the clustered topics(4).
2025-06-30 20:29:01,834 - BERTopic - Representation - Fine-tuning topics using representation models.
2025-06-30 20:29:04,231 - BERTopic - Representation - Completed ✓
100%|██████████| 4/4 [00:02<00:00,  1.47it/s]